server:
  port: 8080
  servlet:
    context-path: /maikun
logging:
  file: /Users/chengchen/Desktop/JavaTraining/products/helloworld.log
  level:
     com.maikun.service.buyer.helloworld.HelloWorldController: debug

spring:
  rabbitmq:
      host: 193.112.35.196
      port: 5672
      username: guest
      password: guest
      # 消息发送到交换机确认机制,是否确认回调
      publisher-confirms: true
      # 开启发送失败退回
      publisher-returns: true
      # 开启ACK
      #listener.direct.acknowledge-mode=manual
      #listener.simple.acknowledge-mode=manual
  redis:
      host: 193.112.35.196
      port: 6379
      password:
      pool:
      timeout: 5000
  jpa:
    database: MySQL
    hibernate:
      ddl-auto: update
    show-sql: true
    # Hibernate默认创建的表是myisam引擎，而不是innodb
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        dialect: com.maikun.service.buyer.configuration.MySQL5DialectUTF8
  jackson:
      default-property-inclusion: non_null
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      username: grass
      password: mooncake
      url: jdbc:mysql://193.112.35.196:3306/product?characterEncoding=utf-8&useSSL=false

#RabbitMQ Exchang and Queue name
mq:
  requestProductsQueue: requestProductsQueue
  responseProductsQueue: responseProductsQueue
  productDirectExchange: productDirectExchange
  requestProductsQueueRoutingKey: request-product-list
  responseProductsQueueRoutingKey: response-product-list

# JWT 认证配置
jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800 #token七天不过期
  tokenHead: "Bearer "
  exceptUrl: "/auth/**"
